version: '3.11'

services:
  
  test_db:
    
    image: postgres:10
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck :
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval : 5s
      timeout : 5s
      retries : 5


  app:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=test_db
      - POSTGRES_PORT=5432
      ports:
      - "8000:8000"
      depends_on:
        test_db:
          condition: service_healthy
